apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: toolserver
  name: toolserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: toolserver
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: toolserver
    spec:
      containers:
        - args:
            - uvicorn
            - toolserver_app:create_app
            - --factory
            - --host
            - 0.0.0.0
            - --port
            - "9090"
          env:
            - name: TOOLSERVER_RUN_STORE_DIR
              value: /workspace/omnibioai-toolserver/out/runs
          image: toolserver
          livenessProbe:
            exec:
              command:
                - python -c "import urllib.request; urllib.request.urlopen('http://127.0.0.1:9090/health', timeout=2).read(); print('ok')"
            failureThreshold: 30
            periodSeconds: 5
            timeoutSeconds: 5
          name: omnibioai-toolserver
          volumeMounts:
            - mountPath: /workspace
              name: workspace
      restartPolicy: Always
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: workspace
